name: Transporter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  modal_progress_hud: ^0.1.3
  google_maps_flutter: ^1.0.4
  geolocator: ^5.3.0
  geocoder: 
  permission_handler: ^4.4.0
  android_intent: ^0.3.7
  url_launcher: ^5.7.8
  intl: ^0.16.1
  image_picker: ^0.6.7
  image_cropper: ^1.2.3
  flutter_native_image: ^0.0.5
  flutter_polyline_points: ^0.2.1
  http: ^0.12.2
  toast: ^0.1.5
  shared_preferences: ^0.5.8
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/images/Loginsignup/Auto-01.png
    - assets/images/Loginsignup/Blu-logo.png
    - assets/images/Loginsignup/Blu-SubBG-04.png
    - assets/images/Loginsignup/Blu-SubBG-05.png
    - assets/images/Loginsignup/BT-1.png
    - assets/images/Loginsignup/BT-2.png
    - assets/images/Loginsignup/Calender-Icon-01.png
    - assets/images/Loginsignup/DropDown-Icon-01.png
    - assets/images/Loginsignup/Field-01.png
    - assets/images/Loginsignup/Line-1.png
    - assets/images/Loginsignup/Upload-Icon-01.png
    - assets/images/login/BG-1.png
    - assets/images/login/BG-2.png
    - assets/images/signup/Field-01.png
    - assets/images/icons/TRUCK.png
    - assets/images/icons/call-icon.png
    - assets/images/icons/help-icon.png
    - assets/images/icons/MYPROFILE.png
    - assets/images/SkeletonScreenDesign/BackArrow-Icon.png
    - assets/images/SkeletonScreenDesign/BG-01.png
    - assets/images/SkeletonScreenDesign/Big-Icon-Holder.png
    - assets/images/SkeletonScreenDesign/Close-Icon.png
    - assets/images/SkeletonScreenDesign/Header-Bg.png
    - assets/images/SkeletonScreenDesign/Header-Logo.png
    - assets/images/SkeletonScreenDesign/White-BG.png
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
        - asset: assets/fonts/arialbd.ttf
          weight: 600
    - family: Shruti
      fonts:
        - asset: assets/fonts/shruti.ttf
        - asset: assets/fonts/shrutib.ttf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
